---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: centos7.5-vagrant
    box: centos/7
    # centos7.5 image
    # https://app.vagrantup.com/centos/boxes/7
    # https://blog.centos.org/2018/10/updated-centos-vagrant-images-available-v1809-01/
    box_version: "1809.01"
    cpus: 2
    memory: 2048
provisioner:
  name: ansible
  options:
    become: true
  playbooks:
    converge: ../../{{cookiecutter.playbook_name}}.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../tests
  options:
    verbose: true
  lint:
    name: flake8

# vim: tabstop=2 shiftwidth=2
